language: python
sudo: false


env:
  global:
    - PIP_DEPS="nose coveralls flake8"

python:
  - '2.7'
  - '3.6'


install:
- pip install $PIP_DEPS
- pip install -r requirements.txt

script:
- nosetests -v

after_success:
- coveralls
